### ISSUE TITLE
C# / .NET Core Version?

### ISSUE THREAD

**Issue by briansboyd** [aws-samples/amazon-chime-voiceconnector-transcription#28]
We're on WIndows and have no Java developer resources.  Are there plans to make this available in C#/ .NET Core?

**Comment by sachgo** [comment]
Currently we do not have a plan to build this app in C#/.NET Core.

**Comment by briansboyd** [comment]
Thanks @sachgo.  For me to work with these two repos, will I need to compile these codes locally or are there pre-compiled libraries that I can use?  Thanks!

**Comment by sachgo** [comment]
For amazon-chime-voiceconnector-transcription repo you can download the package from latest release and deploy, but for chime-voiceconnector-agent-assist repo you will need to clone it locally to deploy.

**Comment by briansboyd** [comment]
Thank you for the quick response.
